- name: 确保下载目录存在
  file: path={{Downloads}} state=directory
- name: 拷贝PHP
  synchronize: src={{Modules.PHP.name}}-{{Modules.PHP.version}} dest={{Downloads}} recursive=yes delete=yes
- name: 创建PHP安装路径
  file: path={{Modules.PHP.prefix}} state=directory
- name: 配置PHP
  environment: "{{Modules.PHP.environ}}"
  shell: chdir="{{Downloads}}/{{Modules.PHP.name}}-{{Modules.PHP.version}}" ./configure --prefix={{Modules.PHP.prefix}} {{Modules.PHP.with_args}}
- name: 编译PHP
  shell: chdir="{{Downloads}}/{{Modules.PHP.name}}-{{Modules.PHP.version}}" make 
- name: 安装PHP
  shell: chdir="{{Downloads}}/{{Modules.PHP.name}}-{{Modules.PHP.version}}" make install
- name: 同步php.ini
  template: src={{Modules.PHP.config_file}} dest="{{Modules.PHP.prefix}}/etc/php.ini" mode=644
- name: 同步php-fpm.conf
  template: src={{Modules.PHP.fpm_config_file}} dest="{{Modules.PHP.prefix}}/etc/php-fpm.conf" mode=644
- name: 同步www.conf
  template: src={{Modules.PHP.fpm_www_file}} dest="{{Modules.PHP.prefix}}/etc/php-fpm.d/www.conf" mode=644
- name: 生成启动脚本
  shell: cp "{{Downloads}}/{{Modules.PHP.name}}-{{Modules.PHP.version}}/sapi/fpm/init.d.php-fpm" /etc/init.d/php-fpm; chmod +x /etc/init.d/php-fpm
- name: 添加到PATH
  lineinfile: dest=/etc/profile line="export PATH=/usr/local/php7/bin:/usr/local/php7/sbin:$PATH" backup=yes
  notify:
  - reload env
