---
# vars file for PHP7
DepPkgs:
- httpd-devel
- zlib-devel
- libxml2-devel
- bzip2-devel
- curl-devel
- libicu-devel
- libXpm-devel
- readline-devel
- libtool
- libjpeg-devel
- libpng-devel
- freetype-devel
PHPInsDir: /usr/local/php7
Downloads: /opt/software

Modules:
  libmcrypt:
    name: libmcrypt
    version: 2.5.8
    prefix: /usr/local/libmcrypt
  mhash:
    name: mhash
    version: 0.9.9.9
    prefix: /usr/local/mhash
  mcrypt:
    name: mcrypt
    version: 2.6.8
    prefix: /usr/local/mcrypt
    with_args: --with-libmcrypt-prefix=/usr/local/libmcrypt/
    environ: 
      LD_LIBRARY_PATH: /usr/local/mhash/lib:/usr/local/libmcrypt/lib
      LDFLAGS: -L/usr/local/mhash/lib -I/usr/local/mhash/include
      CFLAGS: -I/usr/local/mhash/include
  fontconfig:
    name: fontconfig
    version: 2.11.94
    prefix: /usr/local/fontconfig
  GD:
    name: libgd
    version: 2.1.0
    prefix: /usr/local/gd
    with_args: --with-jpeg --with-png --with-freetype -with-fontconfig=/usr/local/fontconfig --with-xpm
  ImageMagick:
    name: ImageMagick
    version: 7.0.1-1
    prefix: /usr/local/imagemagick7
  libmemcached:
    name: libmemcached
    version: 1.0.18
    include: /usr/local/include/libmemcached
  PHP:
    name: php
    version: 7.1.2
    prefix: /usr/local/php7
    with_args: --with-config-file-path=/usr/local/php7/etc --enable-inline-optimization --disable-debug --with-apxs2=/usr/sbin/apxs --disable-rpath --enable-shared --enable-opcache --with-mysqli --with-pdo-mysql --with-gettext --enable-mbstring --with-iconv --enable-intl --with-mcrypt=/usr/local/libmcrypt --with-mhash --with-openssl --enable-bcmath --enable-soap --with-libxml-dir --enable-pcntl --enable-shmop --enable-sysvmsg --enable-sysvsem --enable-sysvshm --enable-sockets --with-curl --with-zlib --enable-zip --with-bz2 --with-readline --enable-calendar  --enable-ftp --enable-fpm --enable-cgi --with-fpm-user=www --with-fpm-group=www --with-gd --enable-gd-native-ttf --with-freetype-dir --with-png-dir --with-jpeg-dir 
    config_file: php.ini.j2
    fpm_config_file: php-fpm.conf.j2
    fpm_www_file: www.conf.j2
    environ: 
      LD_LIBRARY_PATH: /usr/local/mhash/lib:/usr/local/libmcrypt/lib
      LDFLAGS: -L/usr/local/mhash/lib -I/usr/local/mhash/include
      CFLAGS: -I/usr/local/mhash/include
  igbinary:
    name: igbinary
    version: 2.0.1
  imagick:
    name: imagick
    version: 3.4.3
  redis:
    name: redis
    version: 3.1.1
  memcached:
    name: memcached
    version: 3.0.3
  mongodb:
    name: mongodb
    version: 1.2.7


PHP_Tools:
  phpize: "{{Modules.PHP.prefix}}/bin/phpize"
  php_config: "{{Modules.PHP.prefix}}/bin/php-config"

